version: "3.8"

services:
  dev:
    image: node:12
    command: sleep infinity
    working_dir: /usr/src/gtfs-service-area
    volumes:
      - .:/usr/src/gtfs-service-area

  pipeline:
    image: node:12
    command: npm restart
    working_dir: /usr/src/gtfs-service-area
    volumes:
      - .:/usr/src/gtfs-service-area