version: "3"

services:
  dev:
    image: node:12
    command: sleep infinity
    working_dir: /usr/src/gtfs-service-area
    volumes:
      - .:/usr/src/gtfs-service-area
    links:
      - mongo

  pipeline:
    image: node:12
    command: npm restart
    working_dir: /usr/src/gtfs-service-area
    volumes:
      - .:/usr/src/gtfs-service-area
    links:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - /data/db
