version: "3"

services:
  dev:
    build: .
    command: sleep infinity
    volumes:
      - .:/usr/src/gtfs-service-area
    links:
      - mongo

  gtfs-service-area:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/gtfs-service-area
    links:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - /data/db
